<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * Implements hook_help().
 */
function sand_admin_help($route_name): ?string {
  return sand_help_show_help(__DIR__, $route_name);
}

/**
 * Modify field widgets for which remove button will not be added.
 * 
 * These can be added on the route sand_admin.settings.
 *
 * @param array $skipWidgets
 *   A list with field widgets.
 */
function sand_admin_multiple_field_remove_button_skip_widgets_alter(array &$skipWidgets): void {
  $skip_remove_button_widgets_array = explode("\r\n", \Drupal::config('sand_admin.settings')->get('skip_remove_button'));
  foreach ($skip_remove_button_widgets_array as $widget) {
    $skipWidgets[] = $widget;
  }
}

/**
 * Format code in CKEditor so it's easy to read. JS file is in the same folder as this module.
 */
function sand_admin_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {          
      $settings['editor']['formats'][$text_format_id]['editorSettings']['customConfig'] = base_path() . drupal_get_path('module', 'sand_admin') . '/ckeditor_config.js';           
    }
  }        
}