<?php

/**
 * @file
 * Provides a sandremote entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\sandremote\Entity\Sandremote;
use Drupal\user\UserInterface;
/* For creating a "file" to pass to tika */
use Drupal\file\Entity\File;

/**
 * Implements hook_theme().
 */
function sandremote_theme() {
  return [
    'sandremote' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for sandremote templates.
 *
 * Default template: sandremote.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the sandremote information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sandremote(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sandremote_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish sandremotes.
      $storage = \Drupal::entityTypeManager()->getStorage('sandremote');
      $sandremote_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($sandremote_ids) as $sandremote) {
        $sandremote->set('status', FALSE);
        $sandremote->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize sandremotes.
      $storage = \Drupal::entityTypeManager()->getStorage('sandremote');
      $sandremote_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($sandremote_ids) as $sandremote) {
        $sandremote->setOwnerId(0);
        $sandremote->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sandremote_user_predelete(UserInterface $account) {
  // Delete sandremotes.
  $storage = \Drupal::entityTypeManager()->getStorage('sandremote');
  $sandremote_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $sandremotes = $storage->loadMultiple($sandremote_ids);
  $storage->delete($sandremotes);
}
