adding:
  dependencies:
    module:
      - entity_share_client
  permissions:
    - administer_import_config_entity
    - administer_import_status_entities
    - administer_remote_entity
    - entity_share_client_display_errors
    - entity_share_client_pull_content
removing: {  }
