adding: {  }
removing:
  dependencies:
    config:
      - node.type.application
      - node.type.blog
      - node.type.bucket
      - node.type.business_resource
      - node.type.department
      - node.type.department_document
      - node.type.department_parent
      - node.type.event
      - node.type.location
      - node.type.notification
      - node.type.outreach
      - node.type.outreach2
      - node.type.outreach_article2
      - node.type.resources
      - node.type.sand_gallery
      - node.type.slider_image
      - node.type.webform
  permissions:
    - 'create application content'
    - 'create blog content'
    - 'create department content'
    - 'create department_document content'
    - 'create event content'
    - 'create location content'
    - 'create outreach2 content'
    - 'create outreach_article2 content'
    - 'create resources content'
    - 'create sand_gallery content'
    - 'create slider_image content'
    - 'delete any department_document content'
    - 'delete any event content'
    - 'delete any resources content'
    - 'edit any application content'
    - 'edit any blog content'
    - 'edit any bucket content'
    - 'edit any business_resource content'
    - 'edit any department content'
    - 'edit any department_document content'
    - 'edit any department_parent content'
    - 'edit any event content'
    - 'edit any location content'
    - 'edit any notification content'
    - 'edit any outreach content'
    - 'edit any outreach2 content'
    - 'edit any outreach_article2 content'
    - 'edit any resources content'
    - 'edit any sand_gallery content'
    - 'edit any slider_image content'
    - 'edit own blog content'
    - 'edit own department content'
    - 'edit own department_document content'
    - 'edit own event content'
    - 'edit own location content'
    - 'edit own sand_gallery content'
    - 'edit own slider_image content'
    - 'revert blog revisions'
    - 'revert department revisions'
    - 'revert department_document revisions'
    - 'revert department_parent revisions'
    - 'revert event revisions'
    - 'revert location revisions'
    - 'revert resources revisions'
    - 'revert slider_image revisions'
    - 'view application revisions'
    - 'view blog revisions'
    - 'view department revisions'
    - 'view department_document revisions'
    - 'view department_parent revisions'
    - 'view event revisions'
    - 'view location revisions'
    - 'view outreach revisions'
    - 'view outreach2 revisions'
    - 'view outreach_article2 revisions'
    - 'view resources revisions'
    - 'view slider_image revisions'
    - 'view webform revisions'
