_core:
  default_config_hash: 4G3ZLDsRi9C4iY4bCwOic0mB4J30EDCdhYfFHWClXos
cron_interval: 60
page_limit: 0
remotes:
  training:
    enabled: true
    channels:
      articles:
        enabled: true
        import_config: articles
        operations:
          create: true
          update: true
