<?php

/**
 * @file
 * This module directory contains code examples that we've done.
 */

declare(strict_types=1);

// Bundle Classes.
use Drupal\sand_example\Entity\Bundle\Hero;
use Drupal\sand_example\Entity\Bundle\Article;

/**
 * Implements hook_help().
 */
function sand_example_help($route_name): ?string {
  return sand_help_show_help(__DIR__, $route_name);
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function sand_example_entity_bundle_info_alter(array &$bundles): void {
  //$implemented_bundles = ['article','hero'];

  if (isset($bundles['node']['article'])) {
    $bundles['node']['article']['class'] = Article::class;
  }
  if (isset($bundles['node']['hero'])) {
    $bundles['node']['hero']['class'] = Hero::class;
  }
}


function sand_example_theme(): array {
  /*
   * Desc:
   *  This tells Drupal there is a template called "sand-weather.html.twig".
   * Notes: 
   *  You don't have to do this for a block and can just name the template for
   * the block following Drupal naming convensions.
   */
  return [
    'sand_example' => [
      'variables' => [
        'text' => NULL,
      ],
    ],
  ];
}
