pipelines:
  custom:
    pantheon-downstream:
      - step:
          name: Code updates from Pantheon site
          image: cruno/if-php-cms:1.5.1
          script:
            - ./scripts/pantheon-downstream-pr.sh
  branches:
    'main':
      - step:
          name: Deploy to Pantheon
          image: cruno/if-php-cms:1.5.1
          script:
            - git config user.email "it@ifsight.com"
            - git config user.name "IF IT"
            - git checkout -b test-pantheon-master-merge
            - git remote add pantheon ssh://codeserver.dev.558ccf9c-33c1-459f-a727-08540af54518@codeserver.dev.558ccf9c-33c1-459f-a727-08540af54518.drush.in:2222/~/repository.git
            - git fetch pantheon
            - git checkout master
            - git pull pantheon master
            - git merge main
            - git push pantheon master
  pull-requests:
    '**':
      - step:
          name: Test Pantheon upstream
          image: cruno/if-php-cms:1.5.1
          script:
            - git config user.email "it@ifsight.com"
            - git config user.name "IF IT"
            - git checkout -b test-pantheon-master-merge
            - git remote add pantheon ssh://codeserver.dev.558ccf9c-33c1-459f-a727-08540af54518@codeserver.dev.558ccf9c-33c1-459f-a727-08540af54518.drush.in:2222/~/repository.git
            - git fetch pantheon
            - git checkout pantheon master
            - git pull pantheon master
            - git checkout test-pantheon-master-merge
            - git merge master
