pipelines:
  custom:
    pantheon-downstream:
      - step:
          name: Code updates from Pantheon site
          image: cruno/if-php-cms:1.5.1
          script:
            - ./scripts/pantheon-downstream-pr.sh
  branches:
    'main':
      - step:
          name: Deploy to Pantheon
          image: cruno/if-php-cms:1.5.1
          script:
            - ./scripts/pantheon-upstream.sh
