pipelines:
  custom:
    pantheon-downstream:
      - step:
          name: Code updates from Pantheon site
          image: cruno/if-php-cms:1.5.1
          script:
            - ./scripts/bitbucket-automated-updates-pr.sh
