<?php

/**
 * @file
 * Help functions for City of San Diego.
 */

declare(strict_types=1);

use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function sand_help_help($route_name): ?string {
  return sand_help_show_help(__DIR__, $route_name);
}

/**
 * Show the README.md help file.
 *
 * @param string $directory
 *   The directory the help file is in.
 * @param string $route_name
 *   The route name, so we can use it in a case statement.
 *
 * @return string|null
 *   Return the HTML or NULL if file does not exist.
 */
function sand_help_show_help(string $directory, string $route_name):?string {
  switch ($route_name) {
    case 'help.page.cofsd':
    case 'help.page.sand_datalayer':
    case 'help.page.sand_help':
      /** @var string $text */
      $text = file_get_contents($directory . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
        $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
        $parser = $parser_manager->getDefaultParser([
          'render_strategy' => ['type' => 'none'],
        ]);
        return (string) $parser->parse($text);
      }
  }
  return NULL;
}
