<?php

// Bundle Classes.
use Drupal\sand\Entity\Bundle\Article;
use Drupal\sand\Entity\Bundle\Department;

function sand_entity_bundle_info_alter(array &$bundles): void {
  //$implemented_bundles = ['article','hero'];

  if (isset($bundles['node']['article'])) {
    $bundles['node']['article']['class'] = Article::class;
  }
  if (isset($bundles['node']['blog'])) {
    $bundles['node']['blog']['class'] = Blog::class;
  }
  if (isset($bundles['node']['bucket'])) {
    $bundles['node']['bucket']['class'] = Bucket::class;
  }
  if (isset($bundles['node']['business_resource'])) {
    $bundles['node']['business_resource']['class'] = BusinessResource::class;
  }
  if (isset($bundles['node']['date'])) {
    $bundles['node']['date']['class'] = Date::class;
  }
  if (isset($bundles['node']['department'])) {
    $bundles['node']['department']['class'] = Department::class;
  }
  if (isset($bundles['node']['department_document'])) {
    $bundles['node']['department_document']['class'] = DepartmentDocument::class;
  }
  if (isset($bundles['node']['department_parent'])) {
    $bundles['node']['department_parent']['class'] = DepartmentParent::class;
  }
  if (isset($bundles['node']['digital_archives_photos'])) {
    $bundles['node']['digital_archives_photos']['class'] = DigitalArchivesPhotos::class;
  }
  if (isset($bundles['node']['event'])) {
    $bundles['node']['event']['class'] = Event::class;
  }
  if (isset($bundles['node']['external_data'])) {
    $bundles['node']['external_data']['class'] = ExternalData::class;
  }
  if (isset($bundles['node']['gallery_san_diego'])) {
    $bundles['node']['gallery_san_diego']['class'] = GallerySanDiego::class;
  }
  if (isset($bundles['node']['hero'])) {
    $bundles['node']['hero']['class'] = Hero::class;
  }
  if (isset($bundles['node']['location'])) {
    $bundles['node']['location']['class'] = Location::class;
  }
  if (isset($bundles['node']['mayoral_artifacts'])) {
    $bundles['node']['mayoral_artifacts']['class'] = MayoralArtifacts::class;
  }
  if (isset($bundles['node']['notification'])) {
    $bundles['node']['notification']['class'] = Notification::class;
  }
  if (isset($bundles['node']['outreach'])) {
    $bundles['node']['outreach']['class'] = Outreach::class;
  }
  if (isset($bundles['node']['outreach2'])) {
    $bundles['node']['outreach2']['class'] = Outreach2::class;
  }
  if (isset($bundles['node']['outreach_article2'])) {
    $bundles['node']['outreach_article2']['class'] = OutreachArticle2::class;
  }
  if (isset($bundles['node']['registration'])) {
    $bundles['node']['registration']['class'] = Registration::class;
  }
  if (isset($bundles['node']['resources'])) {
    $bundles['node']['resources']['class'] = Resources::class;
  }
  if (isset($bundles['node']['sidebar_block_context'])) {
    $bundles['node']['sidebar_block_context']['class'] = SidebarBlockContext::class;
  }
  if (isset($bundles['node']['slide'])) {
    $bundles['node']['slide']['class'] = Slide::class;
  }
}











