# Schema for the configuration files of the Sand datalayer module.
sand_admin.settings:
  type: config_object
  label: 'San Diego Admin settings'
  mapping:
    skip_remove_button:
      type: string
      label: 'Skip Remove Button on these widgets'