<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * Implements hook_help().
 */
function sand_weather_help($route_name): ?string {
  return sand_help_show_help(__DIR__, $route_name);
}

/**
 * Implements hook_cron().
 */
function sand_weather_cron() {
  /** @var \Drupal\Core\Queue\DatabaseQueue $queue */
  $queue = \Drupal::service('queue')->get('sand_weather_queue');
  $item = new \stdClass();
  $item->request_time = \Drupal::time()->getRequestTime();

  try {
    $queue->createItem($item);
  } catch (Exception $exception) {
    \Drupal::logger('sand_weather')->error($exception->getMessage(), ['exception' => $exception]);
  }
}

/**
 * Implements hook_theme().
 */
function sand_weather_theme(): array {
  return [
    'sand_weather' => [
      'variables' => [
        'text' => NULL,
        'temp' => NULL,
        'icon' => NULL,
        'wurl' => NULL,
      ],
    ],
  ];
}
