<?php

/**
 * @file
 * Sets the weather information for the header.
 */

declare(strict_types=1);

/**
 * Implements hook_cron().
 */
function sand_weather_cron():void {
  $config = \Drupal::config('sand_weather.settings');
  // Default to a config interval or if not set then default here to 900 secs.
  $config_interval = $config->get('interval');
  $interval = !empty($config_interval) ? $config_interval : 900;

  // We usually don't want to act every time cron runs.
  $next_execution = \Drupal::state()->get('sand_weather.next_execution', 0);
  $request_time = \Drupal::time()->getRequestTime();
  if ($request_time >= $next_execution) {
    /** @var \Drupal\Core\Queue\DatabaseQueue $queue */
    $queue = \Drupal::service('queue')->get('sand_weather_queue');
    $item = new \stdClass();
    $item->request_time = $request_time;
    try {
      $queue->createItem($item);
    }
    catch (Exception $exception) {
      watchdog_exception('sand_weather', $exception);
    }
    $next_execution = $request_time + $interval;
    \Drupal::state()->set('sand_weather.next_execution', $next_execution);
  }
}
