
alert("boone");
alert(JSON.stringify(drupalSettings));

// Drupal.behaviors.sand_hero = {
//   attach: function (context, settings) {
//     variableInQuestion = drupalSettings.sand_hero;
//   }
// }
//{"path":{"baseUrl":"/","scriptPath":null,"pathPrefix":"","currentPath":"node/1","currentPathIsAdmin":false,"isFront":false,"currentLanguage":"en"},"pluralDelimiter":"\u0003","suppressDeprecationErrors":true,"ajaxPageState":{"libraries":"admin_toolbar/toolbar.tree,admin_toolbar/toolbar.tree.hoverintent,admin_toolbar_tools/toolbar.icon,big_pipe/big_pipe,contextual/drupal.contextual-links,contextual/drupal.contextual-toolbar,core/drupal.active-link,core/normalize,datalayer/behaviors,devel/devel-toolbar,fontawesome/fontawesome.svg,fontawesome/fontawesome.svg.shim,history/mark-as-read,mediteran/drupal.nav-tabs,mediteran/global-styling,sand/accordion,sand/atoms,sand/flexslider,sand/fonts,sand/foundation,sand/generic,sand/helpers,sand/magnific,sand/molecules,sand/organisms,sand/slides,sand/tabs,sand/translate,sand/zurb-foundation,sand_hero/hero_js_footer,sand_hero/hero_js_header,shortcut/drupal.shortcut,site_alert/drupal.site_alert,system/base,tb_megamenu/base,tb_megamenu/styles,toolbar/toolbar,toolbar/toolbar.escapeAdmin,tour/tour,user/drupal.user.icons","theme":"sand","theme_token":null},"ajaxTrustedUrl":[],"bigPipePlaceholderIds":{"callback=Drupal%5CCore%5CRender%5CElement%5CStatusMessages%3A%3ArenderMessages&args%5B0%5D&token=_HAdUpwWmet0TOTe2PSiJuMntExoshbm1kh2wQzzzAA":true,"callback=Drupal%5Cdevel%5CToolbarHandler%3AlazyBuilder&&token=aWxkb66rXy701UgPJu0fWo_EZYjKGt5PNmbtKiiJmks":true,"callback=user.toolbar_link_builder%3ArenderToolbarLinks&&token=xssKdKFVFD7N0FUPPcC1C7LrqMHpQFVzUhrI4cOeEgs":true,"callback=user.toolbar_link_builder%3ArenderDisplayName&&token=-MH2NzEnTzbzMk0ZGfGgoiw7G3j_-Q1ILWBRVhIOKLI":true,"callback=shortcut.lazy_builders%3AlazyLinks&&token=N1997Wch59v-LxHku3-dD44wjkSNmhegNzlZ8jS0L5I":true},"dataLayer":{"defaultLang":"en","languages":{"en":{"id":"en","name":"English","direction":"ltr","weight":0}}},"lazyLoadUrl":"/term_reference_fancytree/subTree","history":{"nodesToMarkAsRead":{"1":true}},"TBMegaMenu":{"TBElementsCounter":{"column":null},"theme":"sand","tbm-main":{"arrows":"0"}},"siteAlert":{"timeout":300,"workaround_needed":false},"toolbar":{"breakpoints":{"toolbar.narrow":"only screen and (min-width: 16.5em)","toolbar.standard":"only screen and (min-width: 38.125em)","toolbar.wide":"only screen and (min-width: 61em)"},"subtreesHash":"1QTeJTZDoWTSrV7_Dua_BcuDhWv5nfKRNYDopybvftM"},"user":{"uid":"1","permissionsHash":"68e3c3362bbae49a64451c8095f1ea95b2b6fb04846a36943b7edd9546f98a12"}}