field.formatter.settings.sand_hours_formatter:
  type: mapping
  label: 'Office hours display format settings'
  mapping:
    day_format:
      type: string
      label: 'Day notation'
    time_format:
      type: string
      label: 'Time notation'
    compress:
      type: boolean
      label: 'Compress all hours of a day into one set'
    grouped:
      type: boolean
      label: 'Group consecutive days with same hours into one set'
    show_closed:
      type: string
      label: 'Number of days to show'
    closed_format:
      type: text
      label: 'Empty days notation'
    separator:
      type: mapping
      label: 'Separators'
      mapping:
        days:
          type: label
          label: 'Separator between days'
        grouped_days:
          type: label
          label: 'Separator between grouped days'
        day_hours:
          type: label
          label: 'Separator between day and the hours'
        hours_hours:
          type: label
          label: 'Separator between the hours of a time slot'
        more_hours:
          type: label
          label: 'Separator between time slots'
    current_status:
      type: mapping
      label: 'Current status'
      mapping:
        position:
          type: string
          label: 'Current status position'
        open_text:
          type: label
          label: 'Currently open message'
        closed_text:
          type: label
          label: 'Currently closed message'
    exceptions:
      type: mapping
      label: 'Exception dates'
      mapping:
        restrict_exceptions_to_num_days:
          type: integer
          label: 'Restrict exceptions display to x days in future'
        date_format:
          type: string
          label: 'Date format for exception day'
        title:
          type: label
          label: 'Title for exceptions'
    timezone_field:
      type: string
      label: 'Timezone field'
    office_hours_first_day:
      type: string
      label: 'First day of week'
    schema:
      type: mapping
      label: 'Schema.org support'
      mapping:
        enabled:
          type: boolean
          label: 'Enable Schema.org openingHours support'
