adding:
  dependencies:
    module:
      - entity_share_server
      - protected_pages
  permissions:
    - 'administer protected pages configuration'
    - administer_channel_entity
    - 'bypass pages password protection'
    - entity_share_server_access_channels
removing: {  }
