adding: {  }
removing:
  dependencies:
    config:
      - node.type.article
  permissions:
    - 'clone article content'
    - 'create article content'
    - 'edit any article content'
    - 'edit own article content'
    - 'revert article revisions'
    - 'view article revisions'
