# Schema for the configuration files of the San Diego Remote Data Module module.
sand_remote.settings:
  type: config_object
  label: 'San Diego Remote Data Module settings'
  mapping:
    example:
      type: string
      label: 'Example'
