# Schema for the configuration files of the Sand datalayer module.
sand_datalayer.settings:
  type: config_object
  label: 'San Diego Data Layer settings'
  mapping:
    default_department:
      type: integer
      label: 'Default Department Taxonomy Term ID'