_core:
  default_config_hash: H3Vu3xgbyMXr8upGTdVNfvuEr5pb7YhFkhe38BwwvME
entity_types:
  node: node
  block_content: 0
  comment: 0
  contact_message: 0
  content_moderation_state: 0
  crop: 0
  entity_embed_fake_entity: 0
  feeds_subscription: 0
  feeds_feed: 0
  feeds_import_log: 0
  file: 0
  media: 0
  menu_link_content: 0
  path_alias: 0
  redirect: 0
  registration_settings: 0
  registration: 0
  sand_remote: 0
  search_api_task: 0
  shortcut: 0
  sitewide_alert: 0
  smart_date_override: 0
  smart_date_rule: 0
  taxonomy_term: 0
  user: 0
  webform_submission: 0
  paragraph: 0
node_bundles:
  application: application
  article: article
  blog: blog
  bucket: bucket
  department: department
  department_parent: department_parent
  event: event
  location: location
  outreach: outreach
  outreach2: outreach2
  outreach_article2: outreach_article2
  webform: webform
  business_resource: 0
  date: 0
  department_document: 0
  digital_archives_photos: 0
  external_data: 0
  hero: 0
  mayoral_artifacts: 0
  notification: 0
  registration: 0
  resources: 0
  reusable_component: 0
  sand_gallery: 0
  sidebar_block_context: 0
  slide: 0
0_bundles: null
file_bundles:
  file: 0
comment_bundles:
  comment: 0
contact_message_bundles:
  feedback: 0
  personal: 0
block_content_bundles:
  basic: 0
menu_link_content_bundles:
  menu_link_content: 0
shortcut_bundles:
  default: 0
taxonomy_term_bundles:
  tags: 0
user_bundles:
  user: 0
