_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -47
    expanded: false
    enabled: false
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add':
    weight: -50
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  comment__admin:
    weight: -48
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    weight: -46
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    weight: -45
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  entity__sitewide_alert__collection:
    weight: -43
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  admin_toolbar_tools__help:
    weight: -50
    menu_name: admin
    parent: system.admin
    enabled: true
    expanded: false
  system__admin_content:
    weight: -49
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_structure:
    weight: -48
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: -47
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: -46
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: -45
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: -44
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: -43
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  help__main:
    weight: -42
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
