_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -47
    expanded: false
    enabled: false
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add':
    menu_name: admin
    parent: system.admin_content
    weight: -50
    expanded: false
    enabled: true
  comment__admin:
    menu_name: admin
    parent: system.admin_content
    weight: -48
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    menu_name: admin
    parent: system.admin_content
    weight: -46
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    menu_name: admin
    parent: system.admin_content
    weight: -45
    expanded: false
    enabled: true
  entity__sitewide_alert__collection:
    menu_name: admin
    parent: system.admin_content
    weight: -43
    expanded: false
    enabled: true
  admin_toolbar_tools__help:
    menu_name: admin
    parent: system.admin
    weight: -50
    expanded: false
    enabled: true
  system__admin_content:
    menu_name: admin
    parent: system.admin
    weight: -49
    expanded: false
    enabled: true
  system__admin_structure:
    menu_name: admin
    parent: system.admin
    weight: -48
    expanded: false
    enabled: true
  system__themes_page:
    menu_name: admin
    parent: system.admin
    weight: -47
    expanded: false
    enabled: true
  system__modules_list:
    menu_name: admin
    parent: system.admin
    weight: -46
    expanded: false
    enabled: true
  system__admin_config:
    menu_name: admin
    parent: system.admin
    weight: -45
    expanded: false
    enabled: true
  entity__user__collection:
    menu_name: admin
    parent: system.admin
    weight: -44
    expanded: false
    enabled: true
  system__admin_reports:
    menu_name: admin
    parent: system.admin
    weight: -43
    expanded: false
    enabled: true
  help__main:
    menu_name: admin
    parent: system.admin
    weight: -42
    expanded: false
    enabled: true
