_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  asset_injector: 0
  automated_cron: 0
  base_field_override_ui: 0
  better_exposed_filters: 0
  big_pipe: 0
  bigmenu: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cacheexclude: 0
  calendar: 0
  calendar_datetime: 0
  calendar_view: 0
  cancel_button: 0
  captcha: 0
  ckeditor: 0
  cofsd: 0
  color: 0
  colorbox: 0
  colorbox_inline: 0
  colorbox_load: 0
  comment: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  core_event_dispatcher: 0
  crop: 0
  csv_serialization: 0
  customfilter: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  feeds: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  filter_perms: 0
  flexslider: 0
  flexslider_fields: 0
  flexslider_views: 0
  focal_point: 0
  fontawesome: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geofield_map: 0
  geofield_map_extras: 0
  help: 0
  hierarchical_term_formatter: 0
  high_contrast: 0
  history: 0
  honeypot: 0
  hook_event_dispatcher: 0
  html_title: 0
  if_components: 0
  if_dept_permission: 0
  if_sand_customphp: 0
  image: 0
  insert_block: 0
  insert_view: 0
  insert_view_adv: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_effects: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  masquerade: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mysql: 0
  ng_lightbox: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  paranoia: 0
  path: 0
  path_alias: 0
  preprocess_event_dispatcher: 0
  queue_ui: 0
  quick_node_clone: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  registration: 0
  remote_stream_wrapper: 0
  rest: 0
  sand_admin: 0
  sand_datalayer: 0
  sand_help: 0
  sand_hours: 0
  sand_remote: 0
  sand_tamper: 0
  sand_type: 0
  sand_views: 0
  sand_weather: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  search_api: 0
  search_api_attachments: 0
  search_api_solr: 0
  security_review: 0
  semanticviews: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  simplesamlphp_auth: 0
  sitewide_alert: 0
  sitewide_alert_block: 0
  smart_date: 0
  smart_date_recur: 0
  smtp: 0
  standard: 0
  system: 0
  tamper: 0
  taxonomy: 0
  tb_megamenu: 0
  telephone: 0
  term_reference_fancytree: 0
  term_reference_tree: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  ultimate_cron: 0
  user: 0
  views_alias_filter: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_conditional: 0
  views_data_export: 0
  views_dependent_filters: 0
  views_entity_embed: 0
  views_event_dispatcher: 0
  views_exposed_filter_blocks: 0
  views_field_view: 0
  views_selective_filters: 0
  views_taxonomy_term_name_depth: 0
  views_taxonomy_term_name_into_id: 0
  views_templates: 0
  views_ui: 0
  views_year_filter: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  extlink: 1
  pathauto: 1
  update: 1
  externalauth: 10
  password_policy: 10
  views: 10
  contextual_range_filter: 11
  paragraphs: 11
theme:
  bartik: 0
  seven: 0
  mediteran: 0
  sand: 0
  claro: 0
  sand_admin_theme: 0
profile: standard
