_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    weight: -50
    parent: 'menu_link_content:76a05ff8-40ed-4fd1-891f-fd9c76656116'
    menu_name: footer
    enabled: true
    expanded: false
