_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -47
    expanded: false
    enabled: false
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:node__add':
    weight: -49
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  comment__admin:
    weight: -48
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    weight: -46
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    weight: -45
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  entity__sitewide_alert__collection:
    weight: -42
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
