_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  bigmenu: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  cofsd: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  crop: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paranoia: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  security_review: 0
  shortcut: 0
  simple_sitemap: 0
  smart_date: 0
  standard: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  user: 0
  views_ui: 0
  workflows: 0
  pathauto: 1
  views: 10
theme:
  bartik: 0
  seven: 0
  mediteran: 0
profile: standard
