_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  bigmenu: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  crop: 0
  customfilter: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geofield_map: 0
  geofield_map_extras: 0
  help: 0
  history: 0
  honeypot: 0
  hook_event_dispatcher: 0
  if_components: 0
  if_sdmigration: 0
  image: 0
  insert_block: 0
  insert_view: 0
  insert_view_adv: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_effects: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  masquerade: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  paranoia: 0
  path: 0
  path_alias: 0
  preprocess_event_dispatcher: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  registration: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  security_review: 0
  semanticviews: 0
  shortcut: 0
  simple_sitemap: 0
  site_alert: 0
  smart_date: 0
  smart_date_recur: 0
  standard: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  telephone: 0
  term_reference_fancytree: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_migrate: 0
  webform_node: 0
  workflows: 0
  extlink: 1
  pathauto: 1
  update: 1
  password_policy: 10
  views: 10
  paragraphs: 11
theme:
  bartik: 0
  seven: 0
  mediteran: 0
  sand: 0
profile: standard
