cloneable_entities:
  - asset_injector_js
  - asset_injector_css
  - block
  - block_content_type
  - block_content
  - captcha_point
  - comment
  - comment_type
  - contact_form
  - contact_message
  - content_moderation_state
  - content_moderation_notification
  - crop
  - crop_type
  - customfilter
  - editor
  - feeds_feed
  - feeds_feed_type
  - feeds_subscription
  - feeds_import_log
  - field_storage_config
  - field_config
  - file
  - filter_format
  - geocoder_provider
  - image_style
  - language_content_settings
  - configurable_language
  - media_type
  - media
  - menu_link_content
  - metatag_defaults
  - migration
  - migration_group
  - node
  - node_type
  - path_alias
  - behavior_settings
  - rdf_mapping
  - redirect
  - registration
  - registration_settings
  - registration_type
  - rest_resource_config
  - sand_remote_type
  - sand_remote
  - search_page
  - search_api_task
  - search_api_index
  - search_api_server
  - solr_request_handler
  - solr_field_type
  - solr_request_dispatcher
  - solr_cache
  - shortcut
  - shortcut_set
  - simple_sitemap_type
  - simple_sitemap
  - site_alert
  - smart_date_format
  - smart_date_rule
  - smart_date_override
  - menu
  - action
  - taxonomy_term
  - taxonomy_vocabulary
  - tb_megamenu
  - tour
  - ultimate_cron_job
  - user
  - user_role
  - webform_submission
  - webform_options
  - webform
  - workflow
  - pathauto_pattern
  - password_policy
  - view
  - paragraph
  - paragraphs_type
  - date_format
  - entity_view_mode
  - entity_form_mode
  - entity_view_display
  - entity_form_display
  - base_field_override
