entity_type_groups:
  node:
    article:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    blog:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    bucket:
      basic: basic
      advanced: advanced
    department:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    department_document:
      basic: basic
      advanced: advanced
    department_parent:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    outreach2:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    outreach_article2:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_og_description: null
  metatag_maxlength_twitter_cards_description: null
  metatag_maxlength_twitter_cards_title: null
  metatag_maxlength_twitter_cards_label1: null
  metatag_maxlength_twitter_cards_label2: null
tag_scroll_max_height: ''
