_core:
  default_config_hash: ySh6lmKUH2SCk5s532zkdNU9PeyNywkaFGVLbWBbRWY
patterns: "admin*\r\nimagebrowser*\r\nimg_assist*\r\nimce*\r\nnode/add/*\r\nnode/*/edit\r\nprint/*\r\nprintpdf/*\r\nsystem/ajax\r\nsystem/ajax/*"
default_width: 700
lightbox_class: ''
skip_admin_paths: true
renderer: drupal_colorbox
