_core:
  default_config_hash: GzCOg5hzNQf2ysA5beQcYvBNmXUmzCClbQsrm9wWAKE
enforce:
  enable: true
  features:
    accelerometer:
      base: none
    autoplay:
      base: self
    bluetooth:
      base: none
    camera:
      base: none
    gyroscope:
      base: none
    magnetometer:
      base: none
    microphone:
      base: none
    screen-wake-lock:
      base: none
    usb:
      base: none
