features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/sand/images/cosd-logo/cosd-logo-initials-blue-color-sails.svg
favicon:
  use_default: 0
  path: themes/custom/sand/images/favicon.png
  mimetype: image/png
