_core:
  default_config_hash: z1XeiALAQRhGq4dxK84bNVba80zE58qQwaRRAKOZxng
weather_url: 'https://forecast.weather.gov/MapClick.php?lat=32.718814&lon=-117.162222'
interval: 900
enable_logging: 1
weather_api_key: edaf79b9a16c8b57ffe7910ff6a618f3
