_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: sdgovweb_svc@cityofsandiego.onmicrosoft.com
smtp_password: ti88CZ4s7jXw
smtp_from: webmaster@sandiego.gov
smtp_fromname: 'San Diego Webmaster'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: false
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: false
